################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=,preferred,auto,auto

monitorv2 {
  output = DP-3
  mode = 2560x1440@180
  position = 0x0
  scale = 1
  bitdepth = 10
}

monitorv2 {
  output = HDMI-A-1
  mode = 1920x1080@60
  position = -1920x180
  scale = 1
}
